# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [cairo-gh]
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip3 install --upgrade pip3
          pip3 install ecdsa fastecdsa sympy
          curl https://github.com/starkware-libs/cairo-lang/releases/tag/v0.1.0 -o ./cairo-lang-0.1.0.zip
          pip3 install cairo-lang-0.1.0.zip
      - name: compile and run cairo program
        run: |
          cairo-compile $1 --output $1.json
          cairo-run --program=$1.json --print_output --layout=small --program_input=$2 --tracer
